name: artisan

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    container: 
      image: lorisleiva/laravel-docker:7.4
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --no-scripts --prefer-dist --no-progress --no-suggest
    - name: Generate key
      run: php artisan key:generate
    - name: Migrate tables
      run: php artisan migrate
    - name: Run Tests
      run: php artisan test
